version: '3'
services:
  react-app:
    image: node:16
    container_name: projet-bille
    working_dir: /app
    ports:
      - "3001:3000" # Port pour accéder au projet
    volumes:
      - /volume1/docker/projet-bille:/app
    command: sh -c "npm install && npm run build && node server.js"
    restart: unless-stopped
